#!/bin/bash

echo ""
echo "1. Create Resources"
echo ""

terraform \
  -chdir="${TERRAFORM_SOURCE_CODE_DIRECTORY?}" init \
  -reconfigure && \
echo "" && \
terraform \
  -chdir="${TERRAFORM_SOURCE_CODE_DIRECTORY?}" apply \
  -auto-approve

echo ""
