#!/bin/bash

echo ""
echo "3. Foundation"
echo ""

export TF_VAR_key_vault_name=${ARM_STORAGE_ACCOUNT_NAME?}
export TF_VAR_storage_account_access_key=${ARM_STORAGE_ACCOUNT_ACCESS_KEY?}

echo "TF_VAR_storage_account_name........: ${ARM_STORAGE_ACCOUNT_NAME}"
echo "TF_VAR_key_vault_name..............: ${TF_VAR_key_vault_name}"
echo "TF_VAR_resource_group_name.........: ${TF_VAR_resource_group_name}"
echo "TF_VAR_storage_account_access_key..: ${TF_VAR_storage_account_access_key:0:3}"
echo ""

terraform \
  -chdir="${TERRAFORM_SOURCE_CODE_DIRECTORY?}" apply \
  -auto-approve

echo ""
