#!/bin/bash

echo ""
echo "3. Import Terraform local state to Remote Storage Account"
echo ""

BACKEND_FILE_NAME="${HOME}/.terraform.d/backend-foundation.conf"

cat <<EOF > "${BACKEND_FILE_NAME}"
key                  = "foundation.json"
storage_account_name = "${ARM_STORAGE_ACCOUNT_NAME}"
container_name       = "${ARM_STORAGE_ACCOUNT_CONTAINER_NAME}"
access_key           = "${ARM_STORAGE_ACCOUNT_ACCESS_KEY}"
EOF

echo "${BACKEND_FILE_NAME}:"
echo ""
cat ${BACKEND_FILE_NAME}
echo ""

# Change Backend from local to azurerm and copy to output directory
sed -i '/backend.*local/ s/local/azurerm/' "${TERRAFORM_SOURCE_CODE_DIRECTORY?}/provider.tf"

# Inititalize Foundation Remote Backend
terraform \
  -chdir="${TERRAFORM_SOURCE_CODE_DIRECTORY?}" init \
  -backend-config="${BACKEND_FILE_NAME?}" \
  -reconfigure

echo ""
