#!/bin/bash

echo ""
echo "3. Import Terraform local state to Remote Storage Account"
echo ""

echo "ARM_STORAGE_ACCOUNT_NAME...........: ${ARM_STORAGE_ACCOUNT_NAME}"
echo "ARM_STORAGE_ACCOUNT_CONTAINER_NAME.: ${ARM_STORAGE_ACCOUNT_CONTAINER_NAME}"
echo "ARM_STORAGE_ACCOUNT_ACCESS_KEY.....: ${ARM_STORAGE_ACCOUNT_ACCESS_KEY}"

BACKEND_FILE_NAME="backend.conf"

cat <<EOF > "${BACKEND_FILE_NAME}"
key                  = "foundation.json"
storage_account_name = "${ARM_STORAGE_ACCOUNT_NAME}"
container_name       = "${ARM_STORAGE_ACCOUNT_CONTAINER_NAME}"
sas_token            = "${ARM_SAS_TOKEN}"
EOF

echo ""
