#!/bin/bash

echo ""
echo "2. Retrieve Terraform Backend Credentials"
echo ""

function tf_output() {
  OUTPUT_NAME=$1
  terraform -chdir="${TERRAFORM_SOURCE_CODE_DIRECTORY?}" output --raw ${OUTPUT_NAME}
}

export ARM_STORAGE_ACCOUNT_NAME=$(           tf_output storage_account_name)
export ARM_STORAGE_ACCOUNT_CONTAINER_NAME=$( tf_output storage_account_container_name)
export ARM_STORAGE_ACCOUNT_ACCESS_KEY=$(     tf_output storage_account_primary_access_key)

echo "ARM_STORAGE_ACCOUNT_NAME...........: ${ARM_STORAGE_ACCOUNT_NAME}"
echo "ARM_STORAGE_ACCOUNT_CONTAINER_NAME.: ${ARM_STORAGE_ACCOUNT_CONTAINER_NAME}"
echo "ARM_STORAGE_ACCOUNT_ACCESS_KEY.....: ${ARM_STORAGE_ACCOUNT_ACCESS_KEY:0:3}"

echo ""
