#!/bin/bash

echo ""
echo "2. Retrieve Terraform Backend Credentials"
echo ""

export ARM_STORAGE_ACCOUNT_NAME=$(           terraform -chdir="${TERRAFORM_SOURCE_CODE_DIRECTORY?}" output --raw storage_account_name)
export ARM_STORAGE_ACCOUNT_CONTAINER_NAME=$( terraform -chdir="${TERRAFORM_SOURCE_CODE_DIRECTORY?}" output --raw storage_account_container_name)
export ARM_STORAGE_ACCOUNT_ACCESS_KEY=$(     terraform -chdir="${TERRAFORM_SOURCE_CODE_DIRECTORY?}" output --raw storage_account_primary_access_key)

echo ""
